name: localshare
description: "A Flutter app for local file sharing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  file_picker: ^8.3.7
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^5.0.3
  mime: ^1.0.6
  path: ^1.9.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
