name: Android APK Builds

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'

jobs:
  build-release-splits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install Android SDK components
        run: |
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" \
            --install \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "ndk;27.0.12077973"

      - name: Flutter pub get
        run: flutter pub get

      - name: Format check
        run: dart format --set-exit-if-changed .

      - name: Flutter analyze
        run: flutter analyze

      - name: Build release split APKs
        run: flutter build apk --release --split-per-abi

      - name: List build outputs
        run: ls -R build/app/outputs/flutter-apk

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: release-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          if-no-files-found: error

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: release-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          if-no-files-found: error

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: release-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
          if-no-files-found: error

  publish-release:
    permissions:
        contents: write
    needs: build-release-splits
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            dist/release-arm64-v8a/app-arm64-v8a-release.apk
            dist/release-armeabi-v7a/app-armeabi-v7a-release.apk
            dist/release-x86_64/app-x86_64-release.apk
